const ACTION_TYPES = {
  SET_MENU_LIST: "SET_MENU_LIST",
  SET_SUBMENU_LIST: "SET_SUBMENU_LIST",
  SET_PAYMENT_MODES: "SET_PAYMENT_MODES",
  SET_EXTRAS: "SET_EXTRAS",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  SET_CART: "SET_CART",
  SET_PAYMENT_INFO: "SET_PAYMENT_INFO"
};

export default ACTION_TYPES;
